### ISSUE TITLE
Entering the ship's seat can cause the camera to fly off into space.

### ISSUE THREAD

**Issue by Z5aI69A61** [Raicuparta/NomaiVR#121]
I'm using NomaiVR 0.21, Outer Wilds 1.0.5.317 on Epic, the Vive Pro, and the OWML version that was given to me for testing. The first times I piloted the ship were fine, but now it seems that every time I enter the seat, my camera flies up and out of the ship forever.

**Comment by Z5aI69A61** [comment]
It may have something to do with where I'm facing/if I'm sitting or standing IRL. It's hard to get consistent results. I've noticed, though, that when it's going to ping my camera into space, it's much harder to find the "Buckle Up" prompt with my hand-beam thingy. It's also worth noting that the camera resets to my normal position when I exit the seat.

**Comment by SpikeEscape** [comment]
Can confirm, I've just experienced this as well, on Oculus CV1 with NomaiVR 0.21, Outer Wilds 1.0.5

**Comment by TotsnotAI** [comment]
I have the same issue except it happens pretty consistently to me after the first death until I restart the game- so far it hasn't happened before then
