### ISSUE TITLE
Rumor Mode not accessible in the ship's log with Vive bindings.

### ISSUE THREAD

**Issue by Z5aI69A61** [Raicuparta/NomaiVR#122]
I'm using NomaiVR 0.21, Outer WIlds 1.0.5.317 on Epic, the Vive Pro, and the OWML version that was given to me for testing.  
The other view seems to work fine, but I can't switch to rumor mode with the current bindings.

**Comment by Raicuparta** [comment]
Ah yeah, forgot about this. There's no binding for it in any controller. Will need to change the inputs in this mode.

**Comment by Raicuparta** [comment]
Closed by #128 

All secondary (Xbox Y Button) interactions like doze off, open suit options menu, switch ship log mode, are now accessible by holding the interact button. The UI will still show the Xbox Button icons, but that will change in the future.
