### ISSUE TITLE
Ship signalscope UI bound to the hand, even though the scope itself points with the ship.

### ISSUE THREAD

**Issue by Z5aI69A61** [Raicuparta/NomaiVR#123]
I'm using NomaiVR 0.21, Outer Wilds 1.0.5.317 on Epic, the Vive Pro, and the OWML version that was given to me for testing.  
As in the base game, the ship's signalscope points directly ahead, where the ship itself is pointing. However, the UI is tied to the player's right hand.

**Comment by Raicuparta** [comment]
Note to self: bug triggered by opening the pause menu
