### ISSUE TITLE
Seizure-inducing flashight

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/NomaiVR#13]
Flashlight seems to flicker between both eyes. Make it stop!

**Comment by Raicuparta** [comment]
Might also be fixed by #8 ? Need to check!

**Comment by Foohy** [comment]
Appears to be fixed on AMD at least! Working on a HTC Vive/SteamVR/Vega 56.

**Comment by Raicuparta** [comment]
@Foohy thanks for confirming, closed.
