### ISSUE TITLE
Configurable physics refresh rate

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/NomaiVR#220]
Add to config.json

**Comment by Raicuparta** [comment]
Closed by #226

**Comment by DanOlner** [comment]
Hi - was [just reading this](https://steamcommunity.com/app/753640/discussions/1/2568689796946065157/) from the devs, about using a secretsettings.txt file to override the default 60fps framerate. Is this something the VR mod already does? Given that article notes everything runs on that 60fps tick, was wondering if it's affecting smoothness in VR if it's stuck at 60?

**Comment by Raicuparta** [comment]
@DanOlner yes, NomaiVR already sets the physics refresh rate of the game to tge hmd's refresh rate. This issue was about adding an option to override that value, but it was eventually removed. If you want to change the refresh of NomaiVR, you have to change your headset's refresh rate (in stramvr or oculus settings or whatever)
