### ISSUE TITLE
Zooming in with Signalscope doesn't work

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/NomaiVR#34]
Shows a scope overlay on the screen, no zoom.

**Comment by Raicuparta** [comment]
I also makes the zoom sound play forever after using it. I assume this is because the sound plays until a certain zoom level is reached, and in VR that never happens.

**Comment by Raicuparta** [comment]
Changing the FOV in VR seems like it might be problematic. Check this: https://forum.unity.com/threads/gear-vr-camera-fov-zoomed-in.364269/

**Comment by Raicuparta** [comment]
Perhaps scaling the camera parent might work?

**Comment by Raicuparta** [comment]
Could also just move the camera forward. Probably would require that the camera has another parent, and that parent handles the tracking.

**Comment by Raicuparta** [comment]
Disabled zooming completely for now

**Comment by bfallstrom** [comment]
Of note: though zooming is disabled, the control prompt for zooming still exists, which can confuse players new to the VR version (like me!).

**Comment by Raicuparta** [comment]
"zooming" was replaced by the scope lens. The zoom prompt shows the key that toggles the scope.
