### ISSUE TITLE
Input mappings on Oculus touch are weird

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/NomaiVR#43]
A / B / X / Y buttons are not mapped correctly.
Grip inputs are not tracked at all (could be used as a button)
Analog sticks only work one at a time. Using right stick interrupts left stick and vice-versa.

**Comment by Raicuparta** [comment]
https://forum.unity.com/threads/vive-controller-trigger-press.567997/

**Comment by Raicuparta** [comment]
https://valvesoftware.github.io/steamvr_unity_plugin/tutorials/SteamVR-Input.html

**Comment by Lyokanthrope** [comment]
I can confirm similar behavior on the Index controllers.

**Comment by Raicuparta** [comment]
Figured out how to remap VR controller buttons through SteamVR, will leave this open until it's on a release

**Comment by Raicuparta** [comment]
Fixed by completely remapping controls
