### ISSUE TITLE
Good way to open map

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/NomaiVR#62]
Perhaps from the toolbelt? Getting a bit crowded though.

**Comment by SpikeEscape** [comment]
Tool belt isn't a bad idea by any means,

although if [#58](https://github.com/Raicuparta/NomaiVR/issues/58) then the freed up key bind could be used for the map.

Alternatively, to free up space from the "toolbelt" we could reposition the tools to other parts around the body (i.e. grab the scout launcher by reaching behind your right shoulder etc.) this is a layout used by other popular vr games (namely Sairento) and I find it works very well

If that is being considered then you could have 2 tools placed on either hip, 2 tools behind either shoulder, a tool behind the lower back, this would give you room for the scout, signalscope, translator, the map, and even leave a space open for another possible tool in the future.

**Comment by Raicuparta** [comment]
With #71 the map now opens using the right stick click. I will close this for now but might be worth revisiting because of the poor Vive folks that still don't have that many buttons to spare.
