### ISSUE TITLE
Adding unique input to rotate the probes camera

### ISSUE THREAD

**Issue by SpikeEscape** [Raicuparta/NomaiVR#64]
I've noticed that you can change the orientation of the probe with the right stick,
however this doesn't disable the player turning, so if you want to move the probe you also have to spin the character in place.

perhaps a "modifier" button would be the best solution, say if you hold the right trigger (on oculus) with the probe cannon out then the player would stay still and the right stick would control the probe

**Comment by SpikeEscape** [comment]
I totally misinterpreted what these controls were supposed to be haha

my bad, sorry

**Comment by Raicuparta** [comment]
#75 should help with avoiding this kind of problem eventually
