### ISSUE TITLE
Rotating the ships pitch at full speed pulls the camera out of bounds

### ISSUE THREAD

**Issue by SpikeEscape** [Raicuparta/NomaiVR#73]
I've found that holding the right stick straight up and letting the ship's rotation speed up, that the player character would be sucked backwards behind the pilot chair and by pulling the stick down then the player would get pushed forward towards the windshield.

This is happening in ver 0.11, on windows 10 and with Oculus CV1.

**Comment by Raicuparta** [comment]
Reproduced. Can probably fix this by disabling some of the position adjustments while piloting the ship.

**Comment by Raicuparta** [comment]
Fixed in 0.12 by only adjusting body position to real-world head position while in character input mode. Means you can move out of your body in other mods, but it's a good compromise for now.
