### ISSUE TITLE
Stuck in ground after Nomai Statue activation

### ISSUE THREAD

**Issue by SpikeEscape** [Raicuparta/NomaiVR#76]
While playing through a new expedition I got to the cutscene where the statue activates, and once I regained control of my character I found my feet were clipping through the ground and I was unable to move.

**Comment by Raicuparta** [comment]
Seems like it's either this or the player just instantly dies. Could be a similar fix to whatever I do for #73

**Comment by Raicuparta** [comment]
Fixed in 0.12
