### ISSUE TITLE
Tools are not equippable with Vive motion controls

### ISSUE THREAD

**Issue by Z5aI69A61** [Raicuparta/NomaiVR#94]
I'm not sure exactly how they're supposed to function, but no button I can press on the Vive wands allows me to equip the items on my toolbelt. I've put on my space suit and tried every reasonable hand position and button press relative to each tool, but nothing seems to allow me to equip them.

**Comment by Raicuparta** [comment]
It's supposed to be with the grip buttons. Can you check the mappings on SteamVR controller settings? Whatever button you set to "RT" will be used for the tools. Let me know if you can come up with a better configuration.

**Comment by Z5aI69A61** [comment]
@Raicuparta Even with rebound buttons, nothing seems to be working. You're just supposed to put your hand near or inside the tool on your belt and click, right? I've tried everything I can think of and can't get it to work. As a sidenote, the right grip button wasn't bound to RT, or anything for that matter, by default.

**Comment by Raicuparta** [comment]
@Z5aI69A61 Veresion 0.19 uses different bindings. Supposedly in Vive, you should be able to use the right grip button for grabbing the tools from the toolbelt. If you could test it that would be very helpful. The grabbing system is also different so maybe now it works for you?

Unfortunately the VR patching in OWML isn't ready for the latest version of Outer Wilds yet (1.05), so you'll have to test in 1.04 if possible, or just wait a couple days for OWML to be updated.

**Comment by Z5aI69A61** [comment]
@Raicuparta All the new bindings seem to work well. I can grab the toolbelt items as intended now (although if I'm holding something, it lets me switch to any other tool just by hovering over it. This is kind of weird, because it's hard to aim downward without switching). The only thing that I couldn't figure out how to do is exit the options menu.

**Comment by Raicuparta** [comment]
@Z5aI69A61 The "hover to select" bug is here already: https://github.com/Raicuparta/NomaiVR/issues/108

I'll look into the options menu stuff. Thanks!
