### ISSUE TITLE
Add a deadzone to Vive wand touchpads

### ISSUE THREAD

**Issue by Z5aI69A61** [Raicuparta/NomaiVR#95]
Actions like jumping using a press of the right touchpad also triggers a slight turn, no matter how close to the center line of the touchpad you press.

**Comment by Raicuparta** [comment]
Yeah the Vive wands sound like a nightmare to get working... Especially since I can't test them. Are there no deadzone settings in the SteamVR controller settings? Could you check that?

**Comment by Z5aI69A61** [comment]
@Raicuparta There doesn't seem to be a way to add deadzones through Steam's key rebinding UI. It'll let me add deadzones to button presses if the trackpad is configured as a Dpad, but those button presses can't be tied to thumbstick actions.

**Comment by Z5aI69A61** [comment]
@Raicuparta Also, and this is kind of tangential, but the trackpad button that Steam says is bound to Y (I think it's up on the left trackpad?) for some reason opens the start menu instead of equipping the signalscope. I don't know if that's something on your end, or something that Steam is somehow screwing up.

**Comment by Raicuparta** [comment]
> @Raicuparta Also, and this is kind of tangential, but the trackpad button that Steam says is bound to Y (I think it's up on the left trackpad?) for some reason opens the start menu instead of equipping the signalscope.

That is an undocumented feature. It's very confusing but eventually I'll make it less so. "Y" will open the main menu unless you are piloting the ship, in which case it opens the signalscope. Signalscope in character mode is supposed to be equipped only by grabbing it from the toolbelt.

I think the solution to this will be removing as many buttons as possible from the Vive trackpad clicks. For instance, in the latest releases the need for the X button is starting to disappear in character mode at least. If I keep with this progress, eventually we may only need a jump button and a back button, for instance.

 Messing with deadzones in code will be impossible for me without having a Vive to test. Someone with a Vive would need to develop that.

**Comment by Raicuparta** [comment]
@Z5aI69A61 A new version 0.20 is out. It changes the way joystick inputs is done, and allows the game do it its own deadzone and smoothing to the inputs, just like it did with a normal gamepad. Can you check if you still have this problem?

Keep in mind that the mappings may be different than last time you played, so please check the SteamVR controller settings to understand the mappings.

**Comment by Z5aI69A61** [comment]
The deadzones work nicely. Yay!
