### ISSUE TITLE
Rapid white flashes occur after the end of loop memory transfer

### ISSUE THREAD

**Issue by Z5aI69A61** [Raicuparta/NomaiVR#98]
After I die and my memories are sent to the statue, a series of bright flashes occur before I am respawned on Timber Hearth. They are _not_, as far as I can tell, related to the way that SteamVR will occasionally boot you back to a default screen when a program is loading or running slowly.

**Comment by Raicuparta** [comment]
Yeah this epilepsy party also happens some times if you go inside the sun and some other scenarios. Not sure what can be done about it...
